### ISSUE TITLE
Better control over espresso simulations

### ISSUE THREAD

**Issue by SamTov** [christophlohrmann/SwarmRL#13]
I would like to have more control over espresso simulations and to explain this I will give an example.

I want to implement the "wonderful life" training policy in parallel. In order to do this, I need to create one simulation with N particles normally. However, I then need to create N copies of this environment, each with identical position and velocity initialisation, but, with one particle removed. The simplest thing in my mind would be the following:

```python
simulation_runner = MyRunnerSimulation(...)

new_sim = deep copy(simulation_runner)
new_sim.remove_colloids(ids = [])
```

This may already be possible but I am not sure how to do such a thing.

**Comment by christophlohrmann** [comment]
have you tried the deepcopy? Something tells me you will run into "only one system at a time"

Removing a colloid can be done already if you are willing to hack a bit:
``runner.system.part.by_id(your_id).remove()``. But I am pretty sure that will mess with the hdf5, that does not like changing dataset shape.

**Comment by christophlohrmann** [comment]
Thinking about it more, it's probably a better idea for me to provide a function for adding colloids at specific places with specific orientations instead of random. Then you can create a new simulation from scratch with 1 particle removed

**Comment by SamTov** [comment]
> Thinking about it more, it's probably a better idea for me to provide a function for adding colloids at specific places with specific orientations instead of random. Then you can create a new simulation from scratch with 1 particle removed

So I didn't know that the remove thing existed but that would in principle work. However, I had the same concern that I need to somehow re-initialize the whole thing to re-create the database and everything.

**Comment by christophlohrmann** [comment]
re-initializing should not be so bad. as long as it happens in a different instance, or else "only one system at a time"

**Comment by christophlohrmann** [comment]
what you could also do (hacky, but will guaranteed work) is "deactivate" certain colloids.
Use ``runner.system.part.by_id(69).type = 1000``. Where 1000 stands for a type that no other particle has. That will make it not interact with any of the other colloids. You can also do ``.fix = 3*[True]`` to prevent it from diffusing around. The trajectory will still be recorded, you would need to remember yourself which is the particle that was deactivated

**Comment by SamTov** [comment]
Was there any update on this from an API perspective?

**Comment by christophlohrmann** [comment]
I did not write any code if that is what you ask. Would deactivating a colloid like in the comment above work for you or do you really need the particles actually removed?

**Comment by SamTov** [comment]
If the ghost colloid did absolutely nothing to the simulation then sure it is fine.

**Comment by christophlohrmann** [comment]
it will have no interactions with other particles so it will be out in a physics sense. It will still be passed to the force model so you would need to use the new type to filter it out when you calculate actions

**Comment by SamTov** [comment]
That no issue, this is done automatically. So in this case, I would write some wrapper around the simulation to create N new simulations each with one particle missing which means nothing should be done on the API side.
