### ISSUE TITLE
Dead Kernel with external force

### ISSUE THREAD

**Issue by SamTov** [christophlohrmann/SwarmRL#4]
**Describe the bug**
If I try to use the external force function of the espresso simulations I kill my kernel every time. I have tried it with the latest espresso but only from a jupyter environment not directly from the script.

**Comment by christophlohrmann** [comment]
does your ``myconfig.hpp`` contain ``EXTERNAL_FORCES``?

**Comment by SamTov** [comment]
> does your `myconfig.hpp` contain `EXTERNAL_FORCES`?

Yes and it still fails.

When running it in command line I receive the following.
```bash
  what():  Overflow in the image box count while folding a particle coordinate into the primary simulation box. Maybe a particle experienced a huge force.
```

I copied the simulation parameters from the CI and it works now for just a simulation so I guess it was somewhere in the simulation parametrization.

However, it is not working in the RL example.
